apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: q9mhgdzy3-go 
  janus-idp.io/tekton: q9mhgdzy3-go
  backstage.io/kubernetes-id: q9mhgdzy3-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: q9mhgdzy3-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml